package ast

// Visitor defines the interface for a visitor that can traverse the AST.
// Each node type has a corresponding Visit method.
type Visitor interface {
	VisitProgram(n *Program)
	VisitPackageDeclaration(n *PackageDeclaration) // Added
	VisitImportStatement(n *ImportStatement)       // Added
	VisitConstantDeclaration(n *ConstantDeclaration)
	VisitExpressionStatement(n *ExpressionStatement)
	VisitFunctionStatement(n *FunctionStatement)
	VisitTraitDeclaration(n *TraitDeclaration)
	VisitInstanceDeclaration(n *InstanceDeclaration)
	VisitIdentifier(n *Identifier)
	VisitIntegerLiteral(n *IntegerLiteral)
	VisitFloatLiteral(n *FloatLiteral)
	VisitBigIntLiteral(n *BigIntLiteral)
	VisitRationalLiteral(n *RationalLiteral)
	VisitBooleanLiteral(n *BooleanLiteral)
	VisitNilLiteral(n *NilLiteral)
	VisitTupleLiteral(n *TupleLiteral)
	VisitPrefixExpression(n *PrefixExpression)
	VisitInfixExpression(n *InfixExpression)
	VisitOperatorAsFunction(n *OperatorAsFunction)
	VisitAssignExpression(n *AssignExpression)
	VisitPatternAssignExpression(n *PatternAssignExpression)
	VisitCallExpression(n *CallExpression)
	VisitTypeApplicationExpression(n *TypeApplicationExpression)
	VisitBlockStatement(n *BlockStatement)
	VisitIfExpression(n *IfExpression)
	VisitTypeDeclarationStatement(n *TypeDeclarationStatement)
	VisitNamedType(n *NamedType)
	VisitTupleType(n *TupleType)
	VisitFunctionType(n *FunctionType)
	VisitDataConstructor(n *DataConstructor)
	VisitMatchExpression(n *MatchExpression)
	VisitWildcardPattern(n *WildcardPattern)
	VisitLiteralPattern(n *LiteralPattern)
	VisitIdentifierPattern(n *IdentifierPattern)
	VisitConstructorPattern(n *ConstructorPattern)
	VisitTuplePattern(n *TuplePattern)
	VisitAnnotatedExpression(n *AnnotatedExpression)
	VisitSpreadExpression(n *SpreadExpression)
	VisitSpreadPattern(n *SpreadPattern)
	VisitListPattern(n *ListPattern)
	VisitListLiteral(n *ListLiteral)
	VisitIndexExpression(n *IndexExpression)
	VisitStringLiteral(n *StringLiteral)
	VisitInterpolatedString(n *InterpolatedString)
	VisitCharLiteral(n *CharLiteral)
	VisitBytesLiteral(n *BytesLiteral)
	VisitBitsLiteral(n *BitsLiteral)
	VisitPostfixExpression(n *PostfixExpression)
	VisitFunctionLiteral(n *FunctionLiteral)
	VisitRecordLiteral(n *RecordLiteral)
	VisitMapLiteral(n *MapLiteral)
	VisitRecordType(n *RecordType)
	VisitUnionType(n *UnionType)
	VisitRecordPattern(n *RecordPattern)
	VisitTypePattern(n *TypePattern)
	VisitStringPattern(n *StringPattern)
	VisitPinPattern(n *PinPattern)
	VisitMemberExpression(n *MemberExpression)
	// Loops
	VisitForExpression(n *ForExpression)
	VisitBreakStatement(n *BreakStatement)
	VisitContinueStatement(n *ContinueStatement)
}
